//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuroSound_Application.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EuroSound_Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This audio does not use a loop offset.
        /// </summary>
        internal static string AudioNotUseOffset {
            get {
                return ResourceManager.GetString("AudioNotUseOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This audio seems to be corrupt, please load it again.
        /// </summary>
        internal static string AudioProperties_FileCorrupt {
            get {
                return ResourceManager.GetString("AudioProperties_FileCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The audio will not be replaced, this audio is already loaded and stored in this project. The current one will remain..
        /// </summary>
        internal static string AudioPropertiesFormAudioExists {
            get {
                return ResourceManager.GetString("AudioPropertiesFormAudioExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generates an YML file with the hashcodes that this soundbanks uses.
        /// </summary>
        internal static string ButtonGenerateSoundsList {
            get {
                return ResourceManager.GetString("ButtonGenerateSoundsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows the audio data stores in this project properties (channels, frequency, encoding etc..) in a single list.
        /// </summary>
        internal static string ButtonSoundsBankCheckAudios {
            get {
                return ResourceManager.GetString("ButtonSoundsBankCheckAudios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check that all hashcodes used in this project are correct and exists in the hashtable.
        /// </summary>
        internal static string ButtonSoundsBankCheckHashcodes {
            get {
                return ResourceManager.GetString("ButtonSoundsBankCheckHashcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shows information about the linked stream data in this project.
        /// </summary>
        internal static string ButtonSoundsBankCheckStreamData {
            get {
                return ResourceManager.GetString("ButtonSoundsBankCheckStreamData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search for the specified text.
        /// </summary>
        internal static string ButtonSoundsBankSearch {
            get {
                return ResourceManager.GetString("ButtonSoundsBankSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove color from item?.
        /// </summary>
        internal static string ColorDialogRemoveColor {
            get {
                return ResourceManager.GetString("ColorDialogRemoveColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adds a new audio.
        /// </summary>
        internal static string ContextMenuFolder_AddAudio {
            get {
                return ResourceManager.GetString("ContextMenuFolder_AddAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adds a new sound.
        /// </summary>
        internal static string ContextMenuFolder_AddSound {
            get {
                return ResourceManager.GetString("ContextMenuFolder_AddSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Collapse all child nodes.
        /// </summary>
        internal static string ContextMenuFolder_CollapseAll {
            get {
                return ResourceManager.GetString("ContextMenuFolder_CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete the selected folder.
        /// </summary>
        internal static string ContextMenuFolder_Delete {
            get {
                return ResourceManager.GetString("ContextMenuFolder_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expand all child nodes.
        /// </summary>
        internal static string ContextMenuFolder_ExpandAll {
            get {
                return ResourceManager.GetString("ContextMenuFolder_ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opens a sub-form that allows you to move multiples items to a folder.
        /// </summary>
        internal static string ContextMenuFolder_Move {
            get {
                return ResourceManager.GetString("ContextMenuFolder_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete the unused stored audio data.
        /// </summary>
        internal static string ContextMenuFolder_Purge {
            get {
                return ResourceManager.GetString("ContextMenuFolder_Purge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rename folder, not allowed to rename root folders (Audio Data, Sounds, Streamed Sounds).
        /// </summary>
        internal static string ContextMenuFolder_Rename {
            get {
                return ResourceManager.GetString("ContextMenuFolder_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sort items A-&gt;Z.
        /// </summary>
        internal static string ContextMenuFolder_Sort {
            get {
                return ResourceManager.GetString("ContextMenuFolder_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change the node label color for a custom one.
        /// </summary>
        internal static string ContextMenuFolder_TextColor {
            get {
                return ResourceManager.GetString("ContextMenuFolder_TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creates a new folder.
        /// </summary>
        internal static string ContextMenuFolders_New {
            get {
                return ResourceManager.GetString("ContextMenuFolders_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open properties form for the selected sample.
        /// </summary>
        internal static string ContextMenuSample_Properties {
            get {
                return ResourceManager.GetString("ContextMenuSample_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete selected sample.
        /// </summary>
        internal static string ContextMenuSample_Remove {
            get {
                return ResourceManager.GetString("ContextMenuSample_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rename the selected sample.
        /// </summary>
        internal static string ContextMenuSample_Rename {
            get {
                return ResourceManager.GetString("ContextMenuSample_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add a sample to the selected sound.
        /// </summary>
        internal static string ContextMenuSound_AddSample {
            get {
                return ResourceManager.GetString("ContextMenuSound_AddSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export data to an EuroSound Interchange File.
        /// </summary>
        internal static string ContextMenuSound_ExportESIF {
            get {
                return ResourceManager.GetString("ContextMenuSound_ExportESIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open properties form for the selected sound.
        /// </summary>
        internal static string ContextMenuSound_Properties {
            get {
                return ResourceManager.GetString("ContextMenuSound_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete the selected sound.
        /// </summary>
        internal static string ContextMenuSound_Remove {
            get {
                return ResourceManager.GetString("ContextMenuSound_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rename the selected sound.
        /// </summary>
        internal static string ContextMenuSound_Rename {
            get {
                return ResourceManager.GetString("ContextMenuSound_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, cannot add an item with this name, an item with this name already exists.
        /// </summary>
        internal static string Error_Adding_AlreadyExists {
            get {
                return ResourceManager.GetString("Error_Adding_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This audio can&apos;t be loaded because already exists in this project..
        /// </summary>
        internal static string Error_Adding_AudioExists {
            get {
                return ResourceManager.GetString("Error_Adding_AudioExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can&apos;t build the soundbank file without a hashcode. Please set the hashcode for this file in the file preferences..
        /// </summary>
        internal static string Error_BuildSFX_NoHashcode {
            get {
                return ResourceManager.GetString("Error_BuildSFX_NoHashcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, cannot rename this item, an item with this name already exists.
        /// </summary>
        internal static string Error_Rename_AlreadyExists {
            get {
                return ResourceManager.GetString("Error_Rename_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This loop offset is not valid, should be get it from a hi-res source (44100Hz).
        /// </summary>
        internal static string ErrorLoopOffsetNoValid {
            get {
                return ResourceManager.GetString("ErrorLoopOffsetNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error reading this file, seems that is being used by another process..
        /// </summary>
        internal static string ErrorReadingFileIsUsedByAnotherProcess {
            get {
                return ResourceManager.GetString("ErrorReadingFileIsUsedByAnotherProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, the audio file is not correct, the frequency must be in mono, have 22050hz, encoded in PCM and have 16 bits per sample. Do you want that EuroSound tries to convert it with the correct config?.
        /// </summary>
        internal static string ErrorWavFileIncorrect {
            get {
                return ResourceManager.GetString("ErrorWavFileIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, the audio file is not correct, the frequency must be in mono, have 32000hz, encoded in PCM and have 16 bits per sample. Do you want that EuroSound tries to convert it with the correct config?.
        /// </summary>
        internal static string ErrorWavFileIncorrectMusicsMono {
            get {
                return ResourceManager.GetString("ErrorWavFileIncorrectMusicsMono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, the audio file is not correct, the frequency must be in stereo, have 32000hz, encoded in PCM and have 16 bits per sample. Do you want that EuroSound tries to convert it with the correct config?.
        /// </summary>
        internal static string ErrorWavFileIncorrectMusicsStereo {
            get {
                return ResourceManager.GetString("ErrorWavFileIncorrectMusicsStereo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred registering EuroSound File-Types with the shell.
        /// </summary>
        internal static string EuroSoundFile_TypesRegisterdError {
            get {
                return ResourceManager.GetString("EuroSoundFile-TypesRegisterdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EuroSound File-Types registered with the Shell.
        /// </summary>
        internal static string EuroSoundFile_TypesRegisterdOK {
            get {
                return ResourceManager.GetString("EuroSoundFile-TypesRegisterdOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The specified directory does not exists..
        /// </summary>
        internal static string Gen_DirectoryNotExists {
            get {
                return ResourceManager.GetString("Gen_DirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The name can&apos;t be empty.
        /// </summary>
        internal static string Gen_Error_NameIsEmpty {
            get {
                return ResourceManager.GetString("Gen_Error_NameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error reading the file, the file format is corrupt or incorrect.
        /// </summary>
        internal static string Gen_ErrorReading_FileIncorrect {
            get {
                return ResourceManager.GetString("Gen_ErrorReading_FileIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unexcepted error ocurred while reading the file:.
        /// </summary>
        internal static string Gen_ErrorRedingFile {
            get {
                return ResourceManager.GetString("Gen_ErrorRedingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The specified file does not exists..
        /// </summary>
        internal static string Gen_FileNotExists {
            get {
                return ResourceManager.GetString("Gen_FileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no temporal files to clear.
        /// </summary>
        internal static string Gen_NoTemporalFilesStored {
            get {
                return ResourceManager.GetString("Gen_NoTemporalFilesStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temporal files cleared successfully.
        /// </summary>
        internal static string Gen_TemporalFilesRemovedSuccess {
            get {
                return ResourceManager.GetString("Gen_TemporalFilesRemovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This sound should not be added here, is checked as a &quot;Sample Streamed Sound&quot; in the &quot;SFX_Data.h&quot; file. You should add it as a reference in &quot;Streamed Sounds&quot; section and add it to the common file..
        /// </summary>
        internal static string Gen_Warning_StreamedSound {
            get {
                return ResourceManager.GetString("Gen_Warning_StreamedSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The hashtable paths are not correct, please fix them first before continue..
        /// </summary>
        internal static string GenericHashtablesNotCorrect {
            get {
                return ResourceManager.GetString("GenericHashtablesNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected file is not valid, please choose a file with a valid extension.
        /// </summary>
        internal static string GenericUploadedFileWrongExt {
            get {
                return ResourceManager.GetString("GenericUploadedFileWrongExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected hashcode is not defined in the &quot;SFX_Data&quot; hashtable, some properties values are picked from this file. Please add the hashcode to the hashtable before continue. This sound effect will not work correctly in the game without that properties..
        /// </summary>
        internal static string HashcodeNotFoundInSFXDataHashTable {
            get {
                return ResourceManager.GetString("HashcodeNotFoundInSFXDataHashTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: &quot;SFX_Data.h&quot; not found. Please fix the file path before creating or modifying a soundbank..
        /// </summary>
        internal static string Hashcodes_SFXData_NotFound {
            get {
                return ResourceManager.GetString("Hashcodes_SFXData_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: &quot;SFX_Defines.h&quot; not found. Please fix the file path before creating or modifying a soundbank..
        /// </summary>
        internal static string Hashcodes_SFXDefines_NotFound {
            get {
                return ResourceManager.GetString("Hashcodes_SFXDefines_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a New Project.
        /// </summary>
        internal static string InputBoxNewProject {
            get {
                return ResourceManager.GetString("InputBoxNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This item is not used by any other item..
        /// </summary>
        internal static string ItemHasNoDependencies {
            get {
                return ResourceManager.GetString("ItemHasNoDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set project options.
        /// </summary>
        internal static string MenuItem_Edit_FileProps {
            get {
                return ResourceManager.GetString("MenuItem_Edit_FileProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export content to SFX file.
        /// </summary>
        internal static string MenuItem_File_Export {
            get {
                return ResourceManager.GetString("MenuItem_File_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to clean the stored data to make a full reimport?.
        /// </summary>
        internal static string MenuItem_File_LoadListCleanData {
            get {
                return ResourceManager.GetString("MenuItem_File_LoadListCleanData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a new document.
        /// </summary>
        internal static string MenuItem_File_NewProject {
            get {
                return ResourceManager.GetString("MenuItem_File_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save the active document.
        /// </summary>
        internal static string MenuItem_File_Save {
            get {
                return ResourceManager.GetString("MenuItem_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save the active document with a new name.
        /// </summary>
        internal static string MenuItem_File_SaveAs {
            get {
                return ResourceManager.GetString("MenuItem_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set global preferences.
        /// </summary>
        internal static string MenuItem_View_GlobalPreferences {
            get {
                return ResourceManager.GetString("MenuItem_View_GlobalPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show or hide the status bar.
        /// </summary>
        internal static string MenuItem_View_StatusBar {
            get {
                return ResourceManager.GetString("MenuItem_View_StatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Undo the last item deletion.
        /// </summary>
        internal static string MenuItemEdit_Undo {
            get {
                return ResourceManager.GetString("MenuItemEdit_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Undo the last item deletion (not works with samples and folders).
        /// </summary>
        internal static string MenuItemEdit_UndoSoundbanks {
            get {
                return ResourceManager.GetString("MenuItemEdit_UndoSoundbanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close the active document.
        /// </summary>
        internal static string MenuItemFile_Close {
            get {
                return ResourceManager.GetString("MenuItemFile_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quit the application; prompts to save documents.
        /// </summary>
        internal static string MenuItemFile_Exit {
            get {
                return ResourceManager.GetString("MenuItemFile_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import data from EuroSound Interchange File.
        /// </summary>
        internal static string MenuItemFile_ImportESIF {
            get {
                return ResourceManager.GetString("MenuItemFile_ImportESIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open an existing document.
        /// </summary>
        internal static string MenuItemFile_OpenESF {
            get {
                return ResourceManager.GetString("MenuItemFile_OpenESF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Read YML file with a single sound properties and data.
        /// </summary>
        internal static string MenuItemFile_ReadSound {
            get {
                return ResourceManager.GetString("MenuItemFile_ReadSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Read YML file list with multiples sounds.
        /// </summary>
        internal static string MenuItemFile_ReadYml {
            get {
                return ResourceManager.GetString("MenuItemFile_ReadYml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open this document.
        /// </summary>
        internal static string MenuItemFile_RecentFile {
            get {
                return ResourceManager.GetString("MenuItemFile_RecentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display program information, version number and copyright.
        /// </summary>
        internal static string MenuItemHelp_About {
            get {
                return ResourceManager.GetString("MenuItemHelp_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show what changes have been made in the current release.
        /// </summary>
        internal static string MenuItemHelp_CurrentReleaseInfo {
            get {
                return ResourceManager.GetString("MenuItemHelp_CurrentReleaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show online help.
        /// </summary>
        internal static string MenuItemHelp_OnlineHelp {
            get {
                return ResourceManager.GetString("MenuItemHelp_OnlineHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show what changes have been made in recent releases.
        /// </summary>
        internal static string MenuItemHelp_ReleaseInfo {
            get {
                return ResourceManager.GetString("MenuItemHelp_ReleaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a file with the current program preferences.
        /// </summary>
        internal static string MenuItemTools_BackupSettings {
            get {
                return ResourceManager.GetString("MenuItemTools_BackupSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clears the temporal files folder.
        /// </summary>
        internal static string MenuItemTools_ClearTemp {
            get {
                return ResourceManager.GetString("MenuItemTools_ClearTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restore settings from Eurosound Registry file.
        /// </summary>
        internal static string MenuItemTools_RestoreSettings {
            get {
                return ResourceManager.GetString("MenuItemTools_RestoreSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Collapses all folders in the tree control.
        /// </summary>
        internal static string MenuItemView_CollapseTree {
            get {
                return ResourceManager.GetString("MenuItemView_CollapseTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrange icons at the bottom of the window.
        /// </summary>
        internal static string MenuItemWindow_ArrangeIcons {
            get {
                return ResourceManager.GetString("MenuItemWindow_ArrangeIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrange windows so they overlap.
        /// </summary>
        internal static string MenuItemWindow_Cascade {
            get {
                return ResourceManager.GetString("MenuItemWindow_Cascade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrange windows horizontally as non-overlapping tiles.
        /// </summary>
        internal static string MenuItemWindow_TileHorizontal {
            get {
                return ResourceManager.GetString("MenuItemWindow_TileHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arrange windows vertically as non-overlapping tiles.
        /// </summary>
        internal static string MenuItemWindow_TileVertical {
            get {
                return ResourceManager.GetString("MenuItemWindow_TileVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate SFX data binary file.
        /// </summary>
        internal static string MenuTools_SFXDataGenerator {
            get {
                return ResourceManager.GetString("MenuTools_SFXDataGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Output cancelled by user.
        /// </summary>
        internal static string OutputSFXSoundbankCancelled {
            get {
                return ResourceManager.GetString("OutputSFXSoundbankCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred in the output and the file might be corrupt.
        /// </summary>
        internal static string OutputSFXSoundbankErrors {
            get {
                return ResourceManager.GetString("OutputSFXSoundbankErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t assign the selected hashcode to this project, the changes will not be applied.
        /// </summary>
        internal static string ProjectSettings_ErrorHashcode {
            get {
                return ResourceManager.GetString("ProjectSettings_ErrorHashcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This will clear your current search.
        /// </summary>
        internal static string SearcherInfoClearButton {
            get {
                return ResourceManager.GetString("SearcherInfoClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The hashcode has not been found, please add it to the hashtable and click on &quot;Reload Hashtable&quot;.
        /// </summary>
        internal static string SFXDataHashcodeNotFound {
            get {
                return ResourceManager.GetString("SFXDataHashcodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The path assigned to SoX (Sound eXchange) is invalid, can not find the executable file, please correct it before start or load a project..
        /// </summary>
        internal static string SoXInvalidPath {
            get {
                return ResourceManager.GetString("SoXInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There&apos;s no path assigned to SoX (Sound eXchange), please set a path to the application before start or load a project..
        /// </summary>
        internal static string SoXNoPath {
            get {
                return ResourceManager.GetString("SoXNoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reading ESF File.
        /// </summary>
        internal static string StatusBar_ReadingESFFile {
            get {
                return ResourceManager.GetString("StatusBar_ReadingESFFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reading ESIF File.
        /// </summary>
        internal static string StatusBar_ReadingESIFFile {
            get {
                return ResourceManager.GetString("StatusBar_ReadingESIFFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reading MRK File.
        /// </summary>
        internal static string StatusBar_ReadingMRKFile {
            get {
                return ResourceManager.GetString("StatusBar_ReadingMRKFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cleaning temporal folder.
        /// </summary>
        internal static string StatusBar_RemovingTempFiles {
            get {
                return ResourceManager.GetString("StatusBar_RemovingTempFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reading hashcodes data file.
        /// </summary>
        internal static string StatusBar_Status_RadingDataHashcodes {
            get {
                return ResourceManager.GetString("StatusBar_Status_RadingDataHashcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reading hashcodes sound file.
        /// </summary>
        internal static string StatusBar_Status_RadingSoundHashcodes {
            get {
                return ResourceManager.GetString("StatusBar_Status_RadingSoundHashcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reading Directory.
        /// </summary>
        internal static string StatusBar_Status_ReadingDirectory {
            get {
                return ResourceManager.GetString("StatusBar_Status_ReadingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reading YML File.
        /// </summary>
        internal static string StatusBar_Status_ReadingYamlFile {
            get {
                return ResourceManager.GetString("StatusBar_Status_ReadingYamlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready.
        /// </summary>
        internal static string StatusBar_Status_Ready {
            get {
                return ResourceManager.GetString("StatusBar_Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stopping Threads.
        /// </summary>
        internal static string StatusBar_Status_StoppingThreads {
            get {
                return ResourceManager.GetString("StatusBar_Status_StoppingThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The stream sounds file has not been found. Please ensure that the path is correct in the application preferences (view -&gt; preferences).
        /// </summary>
        internal static string StreamFileNotFound {
            get {
                return ResourceManager.GetString("StreamFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error ocurred updating the sounds.
        /// </summary>
        internal static string StreamSoundsUpdatedError {
            get {
                return ResourceManager.GetString("StreamSoundsUpdatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All sounds has been updated successfully.
        /// </summary>
        internal static string StreamSoundsUpdatedSuccess {
            get {
                return ResourceManager.GetString("StreamSoundsUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tree node selected or selected node is a root node, editing root nodes is not allowed..
        /// </summary>
        internal static string TreeView_Error_EditingRootNode {
            get {
                return ResourceManager.GetString("TreeView_Error_EditingRootNode", resourceCulture);
            }
        }
    }
}
